# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer_category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Technology', 'Technology'), ('Home', 'Home'), ('Clothing', 'Clothing'), ('Sport', 'Sport')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
