# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20170421_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_banner',
            field=models.FileField(default='', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.FileField(upload_to=b''),
        ),
    ]
